---
title: "Machine Learning: екзамен"
format: html
---

Екзамен складається із завдання на класифікацію.

::: {.callout-important}
## Важливо

- Ви повинні працювати над цим завданням **самостійно**. Якщо я підозрюю вас у шахрайстві, ви провалите цей курс.
- Ви можете використовувати свої *конспекти*, *книги* та *Інтернет.*
- **Термін виконанн**я: впродовж дня іспиту (`30-05-2023`).
- **Форма звіту**: `PDF`, `HTML`, `DOCX` (GitHub, хмарні сервіси):
  + Варіант 1, надіслати посилання: [форма](https://forms.office.com/Pages/ResponsePage.aspx?id=7QRicv5S3kG0a2BBx8tS738LGDPg6zZBqr1qmv6Wxb5UQjg5VlVFNFVLTk1FTkM4QkNSNTRNVjNSSC4u).
  + Варіант 2, надіслати файл: [форма](https://forms.office.com/Pages/ResponsePage.aspx?id=7QRicv5S3kG0a2BBx8tS738LGDPg6zZBqr1qmv6Wxb5UMlRGTjVCNDhSWU9GVlUySjJZR0wzMVBaUC4u)[^1]

[^1]: Тільки для користувачів `Office365`

:::

# Завдання

Завантажте [файли](https://github.com/Aranaur/ML23/tree/main/exam/data). У вас має бути три файли:

- Навчальний набір даних (`train.csv`).
- Тестовий набір даних (`test.csv`).
- Приклад того, як має виглядати ваш submission-файл (`sample-submission.csv`).

Дані отримані від ресторанів [Yelp](https://www.yelp.com/dataset).

**Ваша задача: Використовуйте дані ресторанів, щоб передбачити, чи матимуть вони рейтинг 4.5 зірки або вище.**

::: {.callout-note}
## Важливо

Ви повинні будете використовувати числову змінну `stars` (рейтинги ресторанів), щоб створити власну змінну результату, яка буде `Yes`, якщо рейтинг ресторану становить 4.5 зірки або вище, і `No`, якщо середня оцінка ресторану нижче 4.5.

*Підказка:* Можливо, ви захочете викинути `stars` (тобто не використовуйте її для прогнозування).

:::

## Основні кроки

1. Завантажте дані та очистіть їх. Оберіть декілька змінних, які найкраще підходять для цієї задачі (мінімум 2). Поясніть свій вибір.<br>
2. Виберіть методи (наприклад, logistic elasticnet, random forest, boosted trees тощо) для цієї задачі класифікації (прогнозування ресторанів із середнім рейтингом вище 4,5). Чому ви обрали ці методи?

::: {.callout-tip}
## Примітка

Ви **не можете** вибрати звичайну МНК регресію або звичайну логістичну регресію.
:::

3. Очистити дані. Цей крок включає нормалізацію, створення нових змінних/взаємодій тощо. Ще раз: коротко поясніть свої рішення.
4. Налаштуйте гіперпараметри вашої моделі. Опишіть, які гіперпараметри ви налаштували та які значення «вибрала» ваша модель.
5. Оцініть `accuracy` вашої моделі на валідаційній вибірці.
6. Оцініть `precision` вашої моделі на валідаційній вибірці.
7. Навчіть свою найкращу модель на повному навчальному наборі даних. Прогнозуйте на тестовому наборі даних. Оцініть ефективність. Збережіть свої прогнози.